### ISSUE TITLE
Can I have an option to automatically add the key into the LocationRecord table?

### ISSUE THREAD

**Issue by stanleychen** [damienbod/AspNetCoreLocalization#30]
It would be nice if I can have an option to add the key into the LocationRecord table if it is not found. There are many keys need to manually add into the table for a new application, I am a kind of lazy to do that.

**Comment by damienbod** [comment]
great idea

**Comment by stanleychen** [comment]
Thanks for reply. I can help to implement this as I need it for my project but I am struggling which class should I put this AddNewKey method.

I tried to put it inside the SqlStringLocalizer but I couldn't find an easy way to pass in the DbConext.

It would help if you can shed some light on this?

**Comment by damienbod** [comment]
@stanleychen sorry for the delay, I will address this, been busy. 

https://github.com/damienbod/AspNet5Localization/blob/master/src/Localization.SqlLocalizer/SqlLocalizationServiceCollectionExtensions.cs#L64

We could do it something like the above extension.

Greetings Damien

**Comment by damienbod** [comment]
Implemented this feature now

https://github.com/damienbod/AspNet5Localization/tree/feature-branch

@stanleychen 
I add a new record everything a resource is not found for the configuration in the startup, even if the culture is not supported. This feature should only be used in development.

https://github.com/damienbod/AspNet5Localization/blob/feature-branch/src/AspNetCoreLocalization/Startup.cs#L30

https://github.com/damienbod/AspNet5Localization/blob/feature-branch/src/AspNetCoreLocalization/Startup.cs#L58

good, bad, view?

Greetings Damien
