### ISSUE TITLE
Package Localization.SqlLocalizer 1.0.9 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package Localization.SqlLocalizer 1.0.9 supports: netcoreapp1.1 (.NETCoreApp,Version=v1.1)

### ISSUE THREAD

**Issue by ericbrunner** [damienbod/AspNetCoreLocalization#35]
Hi Damien,

My Asp.Net Core WebApp must be targeted to full .NET 4.6.1 because several Azure packages , like the `Microsoft.Azure.NotificationHubs v.1.0.8` package are currently not available on .NET Core runtime.

Now I wanted to add your `Localization.SqlLocalizer  v.1.0.9` nuget package but get that error:

`Package Localization.SqlLocalizer 1.0.9 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package Localization.SqlLocalizer 1.0.9 supports: netcoreapp1.1 (.NETCoreApp,Version=v1.1)`

Is there any way or workaround to get it installed?

thanks
Eric

**Comment by damienbod** [comment]
I look into this, see if I can get it to work. At present I target netcoreapp1.1
