### ISSUE TITLE
Return default value if localization not found

### ISSUE THREAD

**Issue by tklawsuc** [damienbod/AspNetCoreLocalization#37]
Is there a way we can return the default localization value if the selected one is not available? e.g. if the default culture is `en-CA` and the client is viewing the site using `fr-CA` and there is no entry for `SharedResource.Phone.fr-CA` then return the value for `SharedResource.Phone.en-CA`. I am creating an app where users can create labels/fields on the site but I don't want to force them to translate to all languages...if they don't provide the other languages then we will just show the default.

**Comment by damienbod** [comment]
Yes
http://localizationsqllocalizer.readthedocs.io/en/latest/configuration.html#displaying-default-keys

Please reopen if you feel this does not annswer your question.

Greetings Damien

**Comment by tklawsuc** [comment]
Thanks Damien. Sorry I should have been clearer. I want to return the default language text...not the key. So if I have a key "Info" and the text for en-CA (default) is "Here is your information" and if there is no entry for fr-CA, then return the text "Here is your information"...not the key "info".

**Comment by damienbod** [comment]
Hi @tklawsuc this should work, I'll check just in case. I'm updating for a new release this week.

Thanks for your input

Greetings Damien

**Comment by tklawsuc** [comment]
Thanks @damienbod
I have the following AddSqlLocalization options
```
var useTypeFullNames = false;
var useOnlyPropertyNames = false;
var returnOnlyKeyIfNotFound = true;
```
Database entry for en-CA:
```
Key: Info
ResourceKey: SharedResource
Text: Here is your information
LocalizationCulture: en-CA
```
View model entry
```
[Display(Name = "Info")]
public string Info { get; set; }
```
When I use `@Html.DisplayNameFor(model => model.Info)`in the view with fr-CA cuture (which has no entry for "Info" in database), I get "Info" (the key). I want it to return the default language (en-CA) text value "Here is your information".

**Comment by damienbod** [comment]
Idea of this, is that the default key, is the default langauge like the default implementation in ASP.NET Core.

Would this work for you?

Greetings Damien

**Comment by tklawsuc** [comment]
Hi @damienbod, if that's the way it works then I'l have to rework the application logic a bit. It's ok though...this functionality actually works well for another piece of the application. Thanks again for the replies and trying to find a solution for my requirements.
