### ISSUE TITLE
How to force Update resources without restart application ?

### ISSUE THREAD

**Issue by houssam-saissi** [damienbod/AspNetCoreLocalization#46]
Hi,

If we modify the data directly in the database, how to reset the location cache without restarting the application?
Using method " **_stringExtendedLocalizerFactory.ResetCache()** ", we find that the data has not been updated?

```
public IActionResult Contact()
        {
            _stringExtendedLocalizerFactory.ResetCache();
            ViewData["Message"] = _homeLocalizerizer["ContactTitle"];

            return View();
        }
```

Any idea ? Thanks ^_^

**Comment by damienbod** [comment]
Hi @houssam-saissi , thanks for reporting.
fixed in https://www.nuget.org/packages/Localization.SqlLocalizer/2.0.2

Could you please verify

**Comment by houssam-saissi** [comment]
Hi, Thanks, it works now :)
