### ISSUE TITLE
Add compatibility with .Net 5.0

### ISSUE THREAD

**Issue by Daedalus72** [damienbod/AspNetCoreLocalization#75]
Hi, 

After today's release of .Net 5.0 from Microsoft, and by converting our project (using AspNetCoreLocalization) to .Net 5.0 we are getting this error on application startup:

![image](https://user-images.githubusercontent.com/20211226/98800870-a7077c00-2419-11eb-9bfe-447357c401d7.png)

So we make the assumption that library must be also converted to .Net 5.0 in order to be compatible.
Thanks a lot !
Vassilios

**Comment by damienbod** [comment]
Will check thanks for the issue

**Comment by Daedalus72** [comment]
Thank you for your awesome job. I have already converted your project to .Net 5 and it works as expected. You only need to convert. If you want I could send you the converted project in order not to bother.
Thanks again.

**Comment by damienbod** [comment]
@Daedalus72 thanks this would be great

**Comment by Daedalus72** [comment]
Of course, my pleasure. Do you want it here as attachment (zip) or you should send my an email to send it to you?

**Comment by Daedalus72** [comment]
Hi Damien, 

I made an OneDrive link for you to download the .Net5 converted solution.

https://1drv.ms/u/s!AqfO-qtKyJORgvBbQ2CrX9llHcxp0Q?e=J2RLoO

Farewell and thank you again for your awesome work.

Vassilios Pallis.

**Comment by Daedalus72** [comment]
@damienbod I have prepared an OneDrive link with the solution, how can I send it to you?

**Comment by damienbod** [comment]
@Daedalus72 Thanks was busy and didn't get back. @CoreDX9  added this in his PR. 

https://github.com/damienbod/AspNetCoreLocalization/pull/79

testing now, does it match yours? 

Greetings Damien

**Comment by damienbod** [comment]
released version 3.0.0
